apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-quarkus-bppneyoa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.cluster-bnl5f.bnl5f.sandbox1132.opentlc.com/tssc/java-quarkus-bppneyoa:ec74d94cd6646bc0929bf71e114e7dc86fb72738@sha256:9c2a323f8058deaf5e8045980bb902c962839c3b68dd029abe2d46634f98e0b4
          name: container-image
